# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiZw4YcuitgkZKuA-eIc_sQWthCKcu-S
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = 'uber.csv'
uber_data = pd.read_csv(file_path)

uber_data = uber_data.loc[:, ~uber_data.columns.str.contains('^Unnamed')]

uber_data['pickup_datetime'] = pd.to_datetime(uber_data['pickup_datetime'])

def haversine(lon1, lat1, lon2, lat2):
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    r = 6371
    return c * r

uber_data['trip_distance_km'] = haversine(uber_data['pickup_longitude'], uber_data['pickup_latitude'],
                                          uber_data['dropoff_longitude'], uber_data['dropoff_latitude'])

uber_data['hour_of_day'] = uber_data['pickup_datetime'].dt.hour

uber_data['trip_purpose'] = uber_data['hour_of_day'].apply(lambda x: 'Business' if 8 <= x <= 18 else 'Personal')


plt.figure(figsize=(12, 6))
sns.boxplot(x='hour_of_day', y='trip_distance_km', hue='trip_purpose', data=uber_data)
plt.title('Uber Trip Mileage Trends by Hour of Day and Purpose')
plt.xlabel('Hour of Day')
plt.ylabel('Trip Distance (km)')
plt.legend(title='Trip Purpose')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(x='trip_purpose', y='trip_distance_km', data=uber_data)
plt.title('Comparative Overview of Trip Lengths for Business and Personal Categories')
plt.xlabel('Trip Purpose')
plt.ylabel('Trip Distance (km)')
plt.show()